export type Recipe = {
  slug: string;
  title: string;
  ethnicity: string;
  category: 'Asian' | 'Middle Eastern' | 'Latin American' | 'European' | 'BBQ' | 'American';
  prepTime: string;
  cookTime: string;
  servings: number;
  description: string;
  ingredients: string[];
  steps: string[];
  nutrition: {
    calories: string;
    protein: string;
    carbs: string;
    highlight: string;
  };
  equipment?: string;
  garrettRating: number;
  garrettTake: string;
};

export const recipes: Recipe[] = [
  {
    slug: 'thai-style-pineapple-fried-rice',
    title: 'Thai-style pineapple fried rice',
    ethnicity: 'Southeast Asian — Thai',
    category: 'Asian',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 6,
    description: 'Savory-sweet jasmine rice wok-tossed with fresh pineapple, shrimp, and toasted cashews — finished with fish sauce and a hit of lime. Leftovers hold beautifully.',
    ingredients: [
      '3 cups jasmine rice (cooked day-ahead, chilled)',
      '1 lb large shrimp, peeled and deveined',
      '2 cups fresh pineapple, diced (use your pineapple)',
      '3 eggs',
      '1 cup frozen peas',
      '4 scallions, sliced',
      '4 garlic cloves, minced',
      '1 tbsp fresh ginger, grated',
      '3 tbsp soy sauce',
      '1 tbsp fish sauce',
      '1 tbsp sesame oil',
      '2 tbsp neutral oil (avocado or canola)',
      '½ cup roasted cashews',
      '1 lime, juiced (use your lemons if preferred)',
      'Fresh cilantro to finish',
    ],
    steps: [
      'Cook jasmine rice a day ahead and refrigerate uncovered. Cold, dry rice is essential — fresh rice holds too much moisture and steams instead of frying, producing clumped, mushy results.',
      'Heat a large pan or wok over high heat until smoking. Add 1 tbsp neutral oil. Sear shrimp 90 seconds per side — don\'t crowd. Remove and set aside.',
      'Add remaining oil. Sauté garlic and ginger 30 seconds until fragrant, then add pineapple and cook 2 minutes to caramelize the edges slightly.',
      'Push everything to the sides. Crack eggs into the center and scramble until just set, then fold into the pineapple mixture.',
      'Add cold rice. Press it flat against the pan and let it sit 60–90 seconds untouched — this creates the lightly crisped crust that distinguishes good fried rice. Toss and repeat once.',
      'Add soy sauce, fish sauce, and sesame oil. Toss to coat evenly. Fold in peas, scallions, and shrimp.',
      'Finish with lime juice and cashews. Top with cilantro. Serve immediately, or refrigerate — reheats well in a hot pan.',
    ],
    nutrition: {
      calories: '~420',
      protein: '28g',
      carbs: '~52g',
      highlight: 'High Vitamin C (pineapple)',
    },
    equipment: 'The Blackstone griddle is ideal here — its large surface area lets you spread all the rice flat for simultaneous crust formation. A standard wok or large skillet works, but you\'ll need to work in batches to avoid steaming.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'smoker-pizza-on-homemade-naan-white-garlic-chicken',
    title: 'Smoker pizza on homemade naan — white garlic + chicken',
    ethnicity: 'South Asian base · American BBQ technique',
    category: 'BBQ',
    prepTime: '25 min active prep + 1 hr dough rest',
    cookTime: '60 min',
    servings: 4,
    description: 'Pillowy hand-stretched naan acts as the crust — topped with roasted garlic cream, smoked chicken thighs, fresh mozzarella, and a lemon-herb finish. The pellet smoker adds a subtle wood note that a conventional oven never touches.',
    ingredients: [
      // Naan dough
      '2¼ tsp instant yeast',
      '1 cup warm water',
      '3 cups all-purpose flour',
      '½ cup plain Greek yogurt',
      '2 tbsp olive oil',
      '1 tsp salt',
      '1 tsp sugar',
      // Toppings
      '3 boneless skinless chicken thighs',
      '6 garlic cloves',
      '4 oz cream cheese, softened',
      '¼ cup heavy cream',
      '8 oz fresh mozzarella, torn',
      '1 lemon, zested and juiced (use your lemons)',
      'Fresh thyme or rosemary',
      'Olive oil, salt, pepper, red pepper flakes',
      'Fresh arugula (optional finish)',
    ],
    steps: [
      'Make naan dough: combine yeast, sugar, and warm water — rest 5 minutes until foamy. Mix in flour, yogurt, olive oil, and salt until a shaggy dough forms. Knead 5–6 minutes until smooth and slightly tacky. Cover and rest 1 hour until doubled.',
      'While dough rests, preheat pellet smoker to 275°F with a mild wood like apple or cherry. Season chicken thighs with salt, pepper, and olive oil. Smoke 45–55 minutes until internal temp hits 165°F. Rest 10 minutes, then slice thin.',
      'Roasted garlic sauce: wrap garlic cloves in foil with a drizzle of olive oil — place directly on the smoker grate the last 30 minutes. When soft, squeeze cloves out and blend with cream cheese and heavy cream until smooth. Season with salt and lemon zest.',
      'Divide dough into 4 equal portions. On a lightly floured surface, stretch or roll each into a roughly oval shape, about ¼ inch thick. Don\'t aim for perfect circles — rustic edges cook better.',
      'Crank smoker to 450°F (or as high as it goes). Place naan directly on the grates. Cook 3–4 minutes until the bottom has grill marks and is set but not fully cooked through.',
      'Flip naan. Working quickly, spread garlic cream, top with torn mozzarella and sliced chicken. Close the lid and cook 4–5 more minutes until cheese is melted and edges are golden.',
      'Remove from smoker. Finish with lemon juice, red pepper flakes, and fresh herbs. Top with arugula if using — it wilts perfectly on the residual heat.',
    ],
    nutrition: {
      calories: '~560',
      protein: '38g',
      carbs: '~48g',
      highlight: 'High Selenium (chicken)',
    },
    equipment: 'The pellet smoker does real work here — both the chicken and garlic absorb smoke during the low-temp phase, then the high-heat finish blisters the naan directly on the grates. A pizza stone placed inside the smoker during preheat is optional but adds bottom crunch.',
    garrettRating: 5,
    garrettTake: 'Perfect and worth every bit of effort. Trish said it was restaurant quality — hard to argue.',
  },
  {
    slug: 'moroccan-spiced-turkey-skillet-with-lemon-couscous',
    title: 'Moroccan-spiced turkey skillet with lemon couscous',
    ethnicity: 'North African — Moroccan',
    category: 'Middle Eastern',
    prepTime: '10 min',
    cookTime: '30 min',
    servings: 4,
    description: 'Ground turkey simmered with warm spices — cumin, coriander, cinnamon — in a tomato-chickpea sauce. Finished with preserved-style lemon brightness and served over fluffy couscous. Bold, warming, and weeknight-fast.',
    ingredients: [
      '1.25 lbs lean ground turkey',
      '1 can (15 oz) chickpeas, drained',
      '1 can (14 oz) crushed tomatoes',
      '1 medium yellow onion, diced',
      '4 garlic cloves, minced',
      '1 tsp each: cumin, coriander, smoked paprika',
      '½ tsp cinnamon',
      '¼ tsp cayenne (adjust to taste)',
      '1 cup chicken broth',
      '2 lemons — zest both, juice one (use your lemons)',
      '1½ cups couscous',
      '1¾ cups boiling water or broth (for couscous)',
      'Fresh parsley or mint to finish',
      '2 tbsp olive oil, salt, pepper',
    ],
    steps: [
      'Bloom the spices: heat olive oil in a large skillet over medium-high. Add onion and cook 4–5 minutes until softened and lightly golden. Add garlic and all dry spices — cook 60 seconds, stirring constantly. Blooming spices in fat unlocks fat-soluble compounds and deepens flavor significantly.',
      'Add ground turkey. Break into small pieces and cook until no pink remains, about 5–6 minutes. Don\'t rush this — full browning develops the Maillard crust that adds depth to the sauce.',
      'Pour in crushed tomatoes, chickpeas, and chicken broth. Stir to combine, scraping any fond from the pan bottom. Reduce heat to medium-low and simmer uncovered 15 minutes until sauce thickens.',
      'While sauce simmers, make couscous: place in a heatproof bowl, pour boiling water or broth over, cover tightly with plastic wrap or a plate. Rest exactly 5 minutes. Fluff with a fork, add lemon zest and a drizzle of olive oil.',
      'Finish the skillet with lemon juice. Taste and adjust salt. The lemon does the work preserved lemon would — bright acidity cuts the warm spices cleanly.',
      'Serve turkey mixture over couscous. Top with fresh parsley or mint. Optionally add a spoonful of Greek yogurt — it cools the heat and adds creaminess without extra cooking.',
    ],
    nutrition: {
      calories: '~470',
      protein: '42g',
      carbs: '~50g',
      highlight: 'High Fiber (chickpeas)',
    },
    equipment: 'No specialty equipment needed here — this is a pure skillet meal. The convection oven setting (if finishing in a covered baking dish) can deepen the sauce further, but stovetop alone is excellent and faster.',
    garrettRating: 5,
    garrettTake: 'This was amazing. Make sure to char the turkey and don\'t be afraid of the cinnamon. Use a timer to make sure you let the spices & garlic cook the desired amount before adding the ground turkey. A standout recipe.',
  },
  {
    slug: 'grilled-chicken-caesar-wraps',
    title: 'Grilled chicken caesar wraps',
    ethnicity: 'Italian-American — homemade dressing',
    category: 'European',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 6,
    description: 'Smoky grilled chicken over crisp romaine, tossed in a punchy homemade caesar — anchovy, garlic, lemon, and parmesan blended into a silky emulsion. Wrapped tight in a toasted flour tortilla with shaved parm and cracked black pepper.',
    ingredients: [
      '3 large chicken breasts',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      'Salt & black pepper',
      'Olive oil',
      '4 anchovy fillets',
      '2 garlic cloves',
      '2 egg yolks',
      '2 tbsp fresh lemon juice',
      '1 tsp Dijon mustard',
      '1 tsp Worcestershire sauce',
      '½ cup olive oil (for dressing)',
      '¼ cup grated parmesan',
      '6 large flour tortillas',
      '3 cups romaine, chopped',
      '½ cup parmesan, shaved',
      'Cracked black pepper',
    ],
    steps: [
      'Pound chicken breasts to even ¾" thickness. Season with garlic powder, smoked paprika, salt, and pepper. Let sit while you make the dressing.',
      'Make the dressing: add anchovies, garlic, egg yolks, lemon juice, Dijon, and Worcestershire to a blender. Blend until smooth — about 20 seconds. With the blender running, stream olive oil in slowly. This gradual addition is what creates the emulsion; dump it all at once and it\'ll break. Finish with parmesan, pulse twice, taste for salt.',
      'Grill chicken on the Blackstone or cast iron over medium-high heat, 5–6 min per side. Pull at 160°F internal, rest 5 min, slice thin against the grain.',
      'Toss romaine with just enough dressing to coat — overdressing makes the wrap soggy. Hold extra dressing on the side.',
      'Toast tortillas on the Blackstone 30 sec per side.',
      'Build: dressed romaine, sliced chicken, shaved parmesan, cracked pepper. Wrap tight and slice on the diagonal.',
    ],
    nutrition: {
      calories: '~490',
      protein: '40g',
      carbs: '~30g',
      highlight: 'High Protein & Omega-3s (anchovies)',
    },
    equipment: 'Blender (Ninja preferred) for emulsifying the dressing. Blackstone griddle for simultaneous tortilla toasting and chicken searing.',
    garrettRating: 4,
    garrettTake: 'Solid option, easily scaleable, and the DIY dressing is worth it.',
  },
  {
    slug: 'korean-chicken-broccoli-plate',
    title: 'Korean chicken & broccoli plate',
    ethnicity: 'East Asian — Korean',
    category: 'Asian',
    prepTime: '20 min',
    cookTime: '20 min',
    servings: 4,
    description: 'A dynamic three-component plate: cool marinated cucumber salad, crispy chow mein noodles, and glossy gochujang-glazed chicken over broccoli. Bold, textured, and deeply satisfying.',
    ingredients: [
      '1 large cucumber, sliced thin',
      '1 tbsp rice vinegar',
      '1 tsp sesame oil',
      '½ tsp chili flake (gochugaru or red pepper flake)',
      '1 tsp soy sauce',
      '1 tsp honey',
      '1 tsp sesame seeds',
      '1 green onion, sliced',
      '8 oz lo mein noodles (or spaghetti)',
      '2 tbsp soy sauce (for noodles)',
      '1 tbsp oyster sauce',
      '1 tsp sesame oil (for sauce)',
      '1 tsp gochujang',
      '3 garlic cloves, minced',
      '2 stalks celery, sliced thin on a bias',
      '½ yellow onion, sliced thin',
      '1 tbsp neutral oil (for noodles)',
      '1 green onion, sliced (garnish)',
      '1.5 lbs chicken breast',
      '2 cups broccoli florets',
      '1 bell pepper, sliced',
      '2 tbsp gochujang (for chicken)',
      '2 tbsp soy sauce (for chicken)',
      '1 tbsp honey (for chicken)',
      '1 tbsp rice vinegar (for chicken)',
      '1 tsp sesame oil (for chicken)',
      '3 garlic cloves, minced (for chicken)',
      '1 tsp fresh ginger, grated',
      '1 tbsp neutral oil (for chicken)',
      'Salt & pepper',
      'Sesame seeds & sliced green onion to finish',
    ],
    steps: [
      'Prepare cucumber salad first: slice cucumber thin. Toss with a pinch of salt and let sit 10 min — this draws out water so the dressing doesn\'t dilute. Pat dry.',
      'Whisk rice vinegar, sesame oil, soy sauce, honey, and chili flake. Toss with cucumber. Top with sesame seeds and green onion. Refrigerate until serving.',
      'Make noodle sauce: mix soy sauce, oyster sauce, sesame oil, and gochujang in a small bowl. Set aside.',
      'Cook noodles until just al dente — 1 minute less than the package says. They\'ll finish cooking in the pan. Drain and toss with a drop of oil to prevent sticking.',
      'Heat wok or large skillet over high heat until smoking. Add neutral oil for noodles, then celery and onion. Stir-fry 2–3 min — you want some color on the onion but celery should stay crisp. Add garlic, stir 30 seconds.',
      'Add noodles and sauce. Toss constantly for 1–2 min until everything is coated and noodles have a little char. Finish with green onion.',
      'While noodles cook, boil broccoli 90 seconds, then transfer to ice water. This sets the bright green color and par-cooks it.',
      'Make chicken glaze: whisk gochujang, soy sauce, honey, rice vinegar, sesame oil, garlic, and ginger. Set aside.',
      'Slice chicken breast against the grain into ½-inch thick planks. Pat completely dry. Season with salt and pepper.',
      'Heat skillet or Blackstone over high heat with neutral oil. Sear chicken planks 3 min per side undisturbed. Work in batches if needed; crowding drops pan temp.',
      'Remove chicken to a plate. In the same pan, add bell pepper and blanched broccoli. Toss 1–2 min. Return chicken, pour glaze over everything, and toss for 30–45 seconds until everything is coated and glossy.',
      'Plate: arrange vegetables first. Lay sliced chicken over the top. Spoon remaining glaze over the chicken. Finish with sesame seeds and green onion.',
    ],
    nutrition: {
      calories: '~490',
      protein: '38g',
      carbs: '~52g',
      highlight: 'High Protein & Vitamin C',
    },
    equipment: 'Wok or large skillet for high-heat stir-frying. Blackstone optional but ideal for simultaneous noodle and chicken cooking.',
    garrettRating: 2.5,
    garrettTake: 'Solid middle-of-the-road dish that\'s very healthy and carried by the sauce addition at the end. The chow mein was also good. A promising recipe we\'ll be revisiting and finding ways to enhance.',
  },
  {
    slug: 'turkish-chicken-shawarma-bowls',
    title: 'Turkish chicken shawarma bowls',
    ethnicity: 'Turkish — Middle Eastern',
    category: 'Middle Eastern',
    prepTime: '20 min (+ 20 min marinade)',
    cookTime: '15 min',
    servings: 6,
    description: 'Warm spiced chicken over herbed rice with a tangy yogurt-garlic sauce. Bold, aromatic, and satisfying without being heavy.',
    ingredients: [
      '2 lbs chicken breast, sliced thin',
      '1 cup 5% Greek yogurt (divided — ½ for marinade, ½ for sauce)',
      '2 tbsp olive oil',
      '1 tbsp cumin',
      '1 tbsp smoked paprika',
      '1 tsp turmeric',
      '1 tsp coriander',
      '1 tsp garlic powder',
      'Salt & pepper',
      '2 cups long-grain white rice',
      '1 can (15 oz) chickpeas, drained',
      '1 cucumber, diced',
      '2 roma tomatoes, diced',
      'Fresh parsley',
      '4 garlic cloves',
      '1 lemon',
    ],
    steps: [
      'Combine ½ cup yogurt, olive oil, cumin, paprika, turmeric, coriander, garlic powder, salt, pepper, and juice of ½ lemon. Coat sliced chicken and marinate 20 min minimum (up to overnight). The yogurt\'s lactic acid tenderizes without making the meat mushy.',
      'Cook rice per package instructions. Fluff and fold in a handful of chopped parsley and a squeeze of lemon.',
      'Get your Blackstone or cast iron ripping hot. Cook chicken in a single layer 3–4 min per side. Don\'t crowd — you want Maillard char on the edges, not steaming. Work in batches if needed.',
      'Make yogurt sauce: mix remaining ½ cup yogurt with 2 minced garlic cloves, juice of ½ lemon, pinch of salt. Thin with 1–2 tbsp water to drizzle consistency.',
      'Build bowls: rice base → chickpeas → sliced chicken → cucumber & tomato → yogurt sauce → fresh parsley. Store components separately for best leftover quality.',
    ],
    nutrition: {
      calories: '~520',
      protein: '42g',
      carbs: '~52g',
      highlight: 'High Protein & Probiotics (yogurt)',
    },
    equipment: 'Cast iron skillet or Blackstone griddle for excellent char on the chicken.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'korean-gochujang-pork-tenderloin',
    title: 'Korean gochujang pork tenderloin',
    ethnicity: 'Korean',
    category: 'Asian',
    prepTime: '10 min',
    cookTime: '35 min',
    servings: 4,
    description: 'Tender, juicy pork glazed in a savory-sweet gochujang sauce with sesame and ginger. A little heat, a lot of depth.',
    ingredients: [
      '1.5 lbs pork tenderloin',
      '3 tbsp gochujang',
      '2 tbsp low-sodium soy sauce',
      '1 tbsp sesame oil',
      '1 tbsp honey',
      '1 tbsp rice vinegar',
      '1 tbsp fresh ginger, grated',
      '3 garlic cloves, minced',
      '2 tsp sesame seeds',
      '3 green onions, sliced',
      '1 lb broccolini or broccoli',
      '1 tbsp neutral oil (avocado or grapeseed)',
      'Salt & pepper',
    ],
    steps: [
      'Whisk gochujang, soy sauce, sesame oil, honey, rice vinegar, ginger, and garlic together. Reserve 2 tbsp separately for finishing.',
      'Pat pork dry — moisture is the enemy of a good sear. Season with salt. Coat with half the glaze.',
      'Heat cast iron over high heat with neutral oil. Sear tenderloin 2 min per side (4 sides) until a dark crust forms. This step builds flavor that roasting alone can\'t.',
      'Transfer to convection oven at 400°F. Roast 12–15 min until internal temp hits 145°F. Convection circulates hot air for even cooking without drying the center. Rest 5 min before slicing.',
      'Toss broccolini in oil, salt, pepper. Roast alongside pork last 10 min until edges are charred.',
      'Slice tenderloin against the grain. Drizzle with reserved glaze. Top with sesame seeds and green onions.',
    ],
    nutrition: {
      calories: '~440',
      protein: '38g',
      carbs: '~20g',
      highlight: 'Lean Cut & Gut-Friendly Gochujang',
    },
    equipment: 'Convection oven for even roasting. Cast iron for initial sear.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'greek-turkey-meatballs-lemon-yogurt-sauce',
    title: 'Greek turkey meatballs with lemon-yogurt sauce',
    ethnicity: 'Greek',
    category: 'European',
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 4,
    description: 'Herb-packed turkey meatballs over orzo with a bright, creamy yogurt sauce spiked with lemon and dill. Fresh, clean, satisfying.',
    ingredients: [
      '1.25 lbs ground turkey',
      '½ cup 5% Greek yogurt (for sauce)',
      '¼ cup breadcrumbs (panko preferred)',
      '1 egg',
      '3 garlic cloves, minced (divided)',
      '1 tsp dried oregano',
      '1 tsp cumin',
      '½ tsp cinnamon',
      'Salt & pepper',
      'Fresh dill (6 tbsp chopped, divided)',
      'Fresh mint',
      '1 lemon',
      '1 lb orzo',
      '2 cups baby spinach',
      '½ red onion, sliced thin',
      '½ cup kalamata olives, halved',
      '2 tbsp olive oil',
    ],
    steps: [
      'Combine turkey, breadcrumbs, egg, 2 minced garlic cloves, oregano, cumin, cinnamon, 2 tbsp chopped dill, salt, and pepper. Mix until just combined — overworking develops protein strands that make meatballs tough. Roll into 1.5-inch balls.',
      'Heat olive oil in an oven-safe skillet over medium-high. Sear meatballs 2 min per side for color, then transfer skillet to 400°F convection oven for 10–12 min. Or bake on a sheet pan at 425°F for 18–20 min.',
      'Cook orzo per package instructions (usually 8–9 min). Drain, toss with a drizzle of olive oil, lemon zest, and baby spinach — residual heat wilts the spinach.',
      'Whisk ½ cup yogurt with 1 minced garlic clove, juice of 1 lemon, remaining fresh dill, salt, and pepper. Thin with 1–2 tbsp water if needed.',
      'Plate: orzo base → meatballs → yogurt sauce → red onion, olives, fresh mint. Finish with lemon zest and a drizzle of good olive oil.',
    ],
    nutrition: {
      calories: '~460',
      protein: '36g',
      carbs: '~48g',
      highlight: 'Lean Protein & Anti-Inflammatory Herbs',
    },
    equipment: 'Oven-safe skillet or sheet pan for finishing meatballs.',
    garrettRating: 3.7,
    garrettTake: 'Solid take on a Shannon classic. Very healthy meal. The herbs are well-balanced and the yogurt sauce is bright. We added a side of sautéed kale.',
  },
  {
    slug: 'chicken-avocado-bacon-wraps',
    title: 'Chicken avocado bacon wraps',
    ethnicity: 'American — Tex-Mex inspired',
    category: 'American',
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 6,
    description: 'Smoky bacon, creamy avocado, and seasoned grilled chicken in a toasted flour tortilla. Bright lime crema keeps it fresh — satisfying without feeling heavy.',
    ingredients: [
      '3 large chicken breasts',
      '6 strips thick-cut bacon',
      '3 ripe avocados',
      '6 large flour tortillas',
      '2 cups romaine, shredded',
      '1 cup cherry tomatoes, halved',
      '½ red onion, thin sliced',
      '½ cup sour cream',
      '1 lime',
      '1 tsp cumin',
      '1 tsp smoked paprika',
      'Salt & pepper',
      'Olive oil',
    ],
    steps: [
      'Season chicken breasts with cumin, smoked paprika, salt, and pepper. Let sit 10 min — even a short rest lets the seasoning penetrate past the surface.',
      'Pound chicken to even thickness (about ¾") with a meat mallet or heavy pan. Uniform thickness = even cook, no dry edges.',
      'Sear chicken in a hot cast iron or on the Blackstone over medium-high heat, 5–6 min per side. Pull at 160°F internal — carryover brings it to 165°F. Rest 5 min, then slice against the grain.',
      'Render bacon in a skillet over medium heat until crisp. Drain on paper towels. Reserve 1 tsp fat if desired for toasting tortillas.',
      'Whisk sour cream with lime juice, a pinch of salt, and a pinch of cumin. This lime crema is your sauce.',
      'Mash avocado with salt and a squeeze of lime. Rough mash — not guacamole smooth.',
      'Toast tortillas directly on the Blackstone or dry skillet 30 sec per side. Adds texture and prevents sogginess.',
      'Build: spread avocado, layer chicken, bacon, romaine, tomatoes, onion, drizzle crema. Wrap tight and slice on the diagonal.',
    ],
    nutrition: {
      calories: '~520',
      protein: '38g',
      carbs: '~35g',
      highlight: 'Healthy Fats (avocado) & Potassium',
    },
    equipment: 'Blackstone griddle ideal for simultaneous tortilla toasting and chicken searing.',
    garrettRating: 4,
    garrettTake: 'A ski trip staple that holds up just as well for work lunches. Reliable and crowd-friendly.',
  },
  {
    slug: 'thai-ginger-cilantro-chicken-stir-fry-in-lettuce-cups',
    title: 'Thai ginger-cilantro chicken stir-fry in lettuce cups',
    ethnicity: 'Thai-inspired / Southeast Asian',
    category: 'Asian',
    prepTime: '35 min (incl. velvet rest)',
    cookTime: '15 min',
    servings: 4,
    description: 'Chicken breasts sliced thin against the grain and velveted before a blistering-hot stir-fry, then served in butter lettuce cups with ginger, lime, cilantro, peanuts, and chili.',
    ingredients: [
      '1.5 lbs chicken breasts, sliced thin against the grain (¼-inch)',
      '1 tsp baking soda',
      '1 tbsp soy sauce',
      '1 tbsp cornstarch',
      '1 tbsp neutral oil',
      '2 heads butter lettuce, leaves separated',
      '1 tbsp neutral oil (for cooking)',
      '5 garlic cloves, minced',
      '1.5-inch knob fresh ginger, finely grated',
      '3 scallions, thinly sliced',
      '1 red bell pepper, thinly sliced',
      '½ cup fresh cilantro, roughly chopped',
      '¼ cup roasted peanuts, crushed',
      '1 lime, cut into wedges',
      '3 tbsp fish sauce',
      '2 tbsp low-sodium soy sauce',
      '1 tbsp fresh lime juice',
      '1 tbsp rice vinegar',
      '1 tsp sesame oil',
      '1 tsp honey',
      '1–2 tsp chili garlic sauce or sambal oelek',
    ],
    steps: [
      'Slice chicken breasts thin against the grain. Toss with baking soda, soy sauce, cornstarch, and oil. Rest 15 min at room temp, then rinse lightly under cold water and pat dry before cooking.',
      'Whisk sauce ingredients together in a small bowl and set aside.',
      'Heat a large skillet or wok over high heat until smoking. Add the oil and cook the chicken in two batches for 60–90 seconds per side until just cooked through with light color. Remove to a plate.',
      'In the same pan, stir-fry garlic and ginger for 45 seconds.',
      'Add the bell pepper and cook 2 minutes until just softened.',
      'Return the chicken to the pan, pour in the sauce, and toss for 60–90 seconds until it lightly coats the meat. Fold in half the scallions and cilantro, then serve in lettuce cups with the remaining scallions, cilantro, peanuts, and lime wedges.',
    ],
    nutrition: {
      calories: '~340',
      protein: '38g',
      carbs: '12g',
      highlight: 'Lean protein + bright citrus',
    },
    equipment: 'Wok or large skillet; sous vide is optional if you want extra-tender breast meat.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'creamy-apple-dill-slaw',
    title: 'Creamy apple-dill slaw',
    ethnicity: 'American / deli-inspired with a fresh twist',
    category: 'American',
    prepTime: '20 min active + 1 hr rest',
    cookTime: '0 min',
    servings: 8,
    description: 'Cool, creamy, herb-forward slaw with crisp apple matchsticks, dill, and ginger for a bright lift that works beautifully with smoky meats.',
    ingredients: [
      '1 medium head green cabbage, thinly shredded',
      '2 medium carrots, julienned or grated',
      '2 crisp apples, cut into matchsticks',
      '4 scallions, thinly sliced',
      '3 tbsp fresh dill, chopped',
      '2 tbsp fresh parsley, chopped (optional)',
      '½ cup Greek yogurt',
      '3 tbsp mayo',
      '1 tbsp apple cider vinegar',
      '1 tsp fresh ginger, finely grated',
      '1 tsp honey',
      '1 tsp Dijon mustard',
      'Salt and white pepper to taste',
    ],
    steps: [
      'Shred the cabbage thinly, toss with 1 tsp salt, and let it sit for 15 minutes so excess moisture can draw out. Squeeze dry before dressing.',
      'Whisk together Greek yogurt, mayo, apple cider vinegar, ginger, honey, and Dijon until smooth. Taste and adjust for brightness and balance.',
      'Combine cabbage, carrots, apple matchsticks, and scallions. Pour the dressing over the top and toss thoroughly.',
      'Fold in dill and parsley. Refrigerate for at least 1 hour before serving so the flavors meld.',
      'Taste again just before serving and adjust salt and pepper as needed.',
    ],
    nutrition: {
      calories: '~110',
      protein: '2g',
      carbs: '12g',
      highlight: 'Fresh crunch + bright herbs',
    },
    equipment: 'Mandoline or sharp knife for thin slicing; sealed container for chilling.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'salsa-verde-asada',
    title: 'Salsa Verde Asada',
    ethnicity: 'Mexican',
    category: 'Latin American',
    prepTime: '10 min',
    cookTime: '6–8 min broil',
    servings: 8,
    description: 'Charred tomatillos and serranos blended with cilantro, avocado, onion, lime, and garlic for a smoky, bright salsa verde that feels restaurant-style but still stays weeknight friendly.',
    ingredients: [
      '450 g fresh tomatillos, husked and rinsed',
      '2 cups fresh cilantro, leaves and tender stems',
      '½ ripe avocado',
      '2 serrano chiles (broiled)',
      '3 garlic cloves',
      '½ white onion, roughly chopped',
      '2 tbsp fresh lime juice',
      '1 tsp kosher salt',
      '2 tbsp cold water, as needed to loosen',
    ],
    steps: [
      'Set the oven to broil on low. Place whole tomatillos and serranos on a foil-lined sheet pan and broil 6 minutes, turning once at 3 minutes, until blistered and lightly charred.',
      'Let the vegetables cool 5 minutes, then add garlic and serranos to a blender first, followed by the broiled tomatillos, onion, lime juice, salt, and avocado. Add the cilantro last.',
      'Pulse 4–5 times, then blend on medium for 15–20 seconds. Aim for slightly textured salsa, not perfectly smooth. Add cold water 1 tbsp at a time if needed.',
      'Taste and adjust salt and lime. If you want more heat, add a fresh serrano half and pulse twice.',
      'Rest the salsa for 10 minutes before serving so the flavors settle and the garlic softens slightly.',
    ],
    nutrition: {
      calories: '~40',
      protein: '1g',
      carbs: '4g',
      highlight: 'Bright green + creamy avocado body',
    },
    equipment: 'Ninja blender or similar, foil-lined sheet pan, broiler.',
    garrettRating: 4,
    garrettTake: 'Refreshing and great. Bright, smoky, and versatile — pairs well with just about anything off the grill.',
  },
  {
    slug: 'shredded-chicken-tacos',
    title: 'Shredded chicken tacos',
    ethnicity: 'Mexican — braised & pulled',
    category: 'Latin American',
    prepTime: '15 min',
    cookTime: '40 min',
    servings: 4,
    description: 'Chile-braised chicken thighs pulled into tender, saucy strands. Loaded into warm corn tortillas with pickled red onion, cotija, and avocado crema — bold and deeply savory.',
    ingredients: [
      '2 lbs boneless chicken thighs',
      '1 can (14 oz) fire-roasted tomatoes',
      '3 chipotle peppers in adobo',
      '4 garlic cloves',
      '1 white onion',
      '1 tsp cumin',
      '1 tsp oregano (Mexican preferred)',
      '1 tsp smoked paprika',
      '½ cup chicken stock',
      '12 small corn tortillas',
      '1 avocado',
      '½ cup sour cream',
      '1 lime',
      '½ cup cotija cheese, crumbled',
      'Fresh cilantro',
      '1 red onion (for pickling)',
      'White vinegar',
      'Salt & olive oil',
    ],
    steps: [
      'Quick-pickle the red onion first: thin-slice, cover with white vinegar, juice of ½ lime, and a pinch of salt. 20 min minimum — they\'ll stay crisp and lose the raw bite.',
      'Blend fire-roasted tomatoes, chipotles, garlic, and ½ the white onion until smooth. This is your braising liquid.',
      'Season chicken thighs generously with salt, cumin, oregano, and smoked paprika.',
      'Sear thighs in a hot Dutch oven or heavy skillet with oil — 3 min per side. You\'re building fond, not cooking through. Don\'t skip this step; it adds depth the braise alone won\'t.',
      'Add blended sauce and chicken stock. Bring to a simmer, cover, and cook 25–30 min over medium-low until chicken shreds easily. The collagen in thighs keeps the meat moist through the braise.',
      'Remove chicken, shred with two forks, then return to the sauce. Simmer uncovered 5 min to let everything reduce and coat.',
      'Blend avocado, sour cream, lime juice, and a pinch of salt into a smooth crema.',
      'Char corn tortillas directly over a gas burner or on the Blackstone — 30 sec per side. Charring adds a slight bitterness that balances the rich braised chicken.',
      'Build tacos: chicken, avocado crema, pickled onion, cotija, cilantro.',
    ],
    nutrition: {
      calories: '~580',
      protein: '42g',
      carbs: '~38g',
      highlight: 'High Protein & Capsaicin (Chipotle)',
    },
    equipment: 'Dutch oven or heavy braising pot. Blender for avocado crema.',
    garrettRating: 3.5,
    garrettTake: 'Solid take on a Reilly family classic. The simmering of the chicken pre-shredding is an amazing addition. Adobo peppers make it spicy and smoky.',
  },
  {
    slug: 'smoked-pork-tenderloin-honey-thyme',
    title: 'Smoked pork tenderloin with honey & thyme',
    ethnicity: 'American BBQ — pellet smoker',
    category: 'BBQ',
    prepTime: '5 min (+ 2–3 hr marinade)',
    cookTime: '1 hr 30 min',
    servings: 4,
    description: 'Pork tenderloin marinated in sweet honey and fresh thyme, then slow-smoked over applewood until just past 145°F. Sweet, smoky, and barely any hands-on work.',
    ingredients: [
      '2 pork tenderloins (1½ lbs each), silverskin removed',
      '½ cup apple juice',
      '3 tbsp honey, warmed',
      '3 tbsp pork & poultry dry rub',
      '¼ cup brown sugar',
      '2 tbsp fresh thyme leaves',
      '½ tbsp black pepper',
    ],
    steps: [
      'Whisk together apple juice, warmed honey, dry rub, brown sugar, thyme, and black pepper in a large bowl.',
      'Add tenderloins to the marinade and coat thoroughly. Cover and refrigerate 2–3 hours.',
      'Preheat the smoker to 225°F with the lid closed for 15 minutes. Enable Super Smoke mode if available — applewood pellets pair especially well with the honey-thyme marinade.',
      'Insert a meat thermometer into the center of one tenderloin. Place both on the grates and smoke until internal temp hits 145°F, about 1–2 hours depending on size and outdoor conditions.',
      'Remove from the smoker and rest 5 minutes before slicing — this lets the juices redistribute instead of running out onto the board.',
    ],
    nutrition: {
      calories: '~310',
      protein: '40g',
      carbs: '~18g',
      highlight: 'Lean Protein & Low Fat',
    },
    equipment: 'Pellet smoker (applewood), meat thermometer, large mixing bowl for the marinade.',
    garrettRating: 5,
    garrettTake: 'The best meat for sandwiches, full stop. Don\'t skip the marinade — it\'s everything. Finish with a torch for that crusted look.',
  },
  {
    slug: 'pepper-jelly-sharp-cheddar-grilled-cheese',
    title: "Pepper jelly & sharp cheddar grilled cheese",
    ethnicity: 'American South — sweet heat classic',
    category: 'American',
    prepTime: '5 min',
    cookTime: '8 min',
    servings: 1,
    description: "Sharp cheddar against a thick layer of Reilly Pepper Co. jelly — sticky, sweet, and genuinely spicy. The anchor sandwich of any grilled cheese spread.",
    ingredients: [
      '2 slices French or Italian loaf, ¾" thick',
      'Sharp or extra-sharp cheddar, thick-sliced',
      "Reilly's pepper jelly, generous on both inner faces",
      'Butter, for the outer crust',
    ],
    steps: [
      'Spread pepper jelly generously on both inner bread faces, then layer in the cheddar.',
      'Butter the outer crusts. Griddle on a medium-low zone — jelly scorches on high heat.',
      'Press with a weight or bacon press and dome to fully melt the cheddar, about 4 minutes per side.',
      'Optional: tuck in a thin layer of smoked turkey or prosciutto — the salt cuts the sweetness nicely.',
    ],
    nutrition: {
      calories: '~430',
      protein: '16g',
      carbs: '~38g',
      highlight: 'Sweet-Heat Pepper Jelly',
    },
    equipment: 'Blackstone griddle (medium-low zone), bacon press or weight, dome lid.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'chorizo-pepper-jack-grilled-cheese-reillys-crema',
    title: "Chorizo, pepper jack & Reilly's crema grilled cheese",
    ethnicity: 'Tex-Mex — smoky and unexpected',
    category: 'American',
    prepTime: '10 min',
    cookTime: '10 min',
    servings: 1,
    description: "Crumbled Mexican chorizo, melted pepper jack, and a pepper-jelly crema spread. Spicy, smoky, and not what anyone expects from grilled cheese.",
    ingredients: [
      '2 slices French or Italian loaf, ¾" thick',
      'Pepper jack cheese',
      'Fresh Mexican chorizo (pork), cooked and crumbled',
      "2 tbsp Greek yogurt or sour cream + 1 tbsp Reilly's jelly, stirred (crema)",
    ],
    steps: [
      'Cook the chorizo first and drain off excess fat.',
      'Stir together the Greek yogurt (or sour cream) and pepper jelly to make the crema; spread on both inner bread faces.',
      'Layer in pepper jack and crumbled chorizo. Griddle over medium heat.',
      'Dome the sandwich — the filling is thick and needs the trapped heat to melt through evenly.',
      "Make a little extra crema to serve table-side as a dip for the rest of the spread.",
    ],
    nutrition: {
      calories: '~520',
      protein: '24g',
      carbs: '~36g',
      highlight: 'Smoky Chorizo & Tangy Crema',
    },
    equipment: 'Blackstone griddle (medium heat), dome lid.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'apple-white-cheddar-honey-dijon-grilled-cheese',
    title: 'Granny Smith apple, sharp white cheddar & honey-Dijon grilled cheese',
    ethnicity: 'American bistro — tart and bright',
    category: 'American',
    prepTime: '8 min',
    cookTime: '8 min',
    servings: 1,
    description: 'Paper-thin Granny Smith against sharp white cheddar, tied together with a swipe of honey-Dijon. The tartness cuts the richness instead of fighting it.',
    ingredients: [
      '2 slices French or Italian loaf, ¾" thick',
      'Sharp white cheddar, thin-sliced',
      'Granny Smith apple, mandoline-thin',
      '1 tsp Dijon mustard + 1 tsp honey, stirred, thin spread inside',
    ],
    steps: [
      'Mandoline the apple paper-thin — thin slices melt into the cheese better than knife-cut.',
      'Spread the honey-Dijon mixture thinly on both inner bread faces. Layer in cheddar and apple.',
      'Griddle on medium-low heat, domed the whole time. The apple needs a couple extra minutes to soften slightly.',
      'Cook about 4 minutes per side. Skip avocado here — apple is the move; adding both crowds the sandwich and muddies the point.',
    ],
    nutrition: {
      calories: '~400',
      protein: '15g',
      carbs: '~34g',
      highlight: 'Tart Apple Brightness',
    },
    equipment: 'Blackstone griddle (medium-low, domed), mandoline.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'argentine-beef-empanadas',
    title: 'Argentine beef empanadas (empanadas de carne)',
    ethnicity: 'Argentine',
    category: 'Latin American',
    prepTime: 'Filling 40 min · Assembly 60 min (+ overnight chill)',
    cookTime: '20–22 min per tray at 400°F',
    servings: 12,
    description: 'Flaky pockets of juicy spiced beef, sweet onion, briny green olive, and chopped egg — the handheld heart of every Argentine gathering. Baked not fried, so they hold beautifully on a party spread.',
    ingredients: [
      '3 lb lean ground beef (90/10)',
      '4 tbsp avocado oil',
      '4 large yellow onions, finely diced',
      '2 red bell peppers, finely diced',
      '8 garlic cloves, minced',
      '4 tsp sweet paprika (pimentón)',
      '4 tsp ground cumin',
      '2 tsp dried oregano',
      '1½ tsp crushed red pepper flakes',
      '1 tbsp salt + black pepper',
      '1 cup beef broth',
      '6 hard-boiled eggs, chopped',
      '1½ cups green olives, chopped',
      '8 scallions, sliced',
      '½ cup raisins (optional — Tucumán style)',
      '48 empanada discs (store-bought Goya Tapas, or homemade masa criolla)',
      '2 eggs + 2 tbsp water (egg wash)',
    ],
    steps: [
      'Sweat onions and bell pepper in avocado oil over medium heat, 10–12 minutes until soft and just golden. The high onion-to-meat ratio is the secret to juicy filling — don\'t rush this. At this volume, work in a wide pan or split into batches so they sweat rather than steam.',
      'Add garlic for 30 seconds, then the beef. Break it up and cook until no longer pink. Add paprika, cumin, oregano, chili flake, salt, and pepper — bloom the spices in the hot fat for a full minute to unlock their oils.',
      'Pour in the beef broth and simmer 4–5 minutes until mostly absorbed but still glossy. Aim for juicy, not soupy — dry filling makes sad empanadas, wet filling blows the seams open.',
      'Off heat, fold in scallions (and raisins if using). Spread across two sheet pans and chill completely, ideally overnight. This is the single most important step: warm filling turns dough gummy and causes leaks. Fold in the chopped egg and olives after chilling so they stay distinct.',
      'Lay a disc in your palm and drop about 2 tbsp cold filling in the center. Leave a clean ½-inch border — overfilling is why they won\'t seal.',
      'Moisten the edge with water, fold into a half-moon, press out the air, and crimp firmly. Fork-press for speed or braid the classic repulgue. A real seal is the only thing keeping the juice inside.',
      'Arrange on parchment-lined trays, brush with egg wash, and bake at 400°F convection for 20–22 minutes until deep golden. Work in batches — crowding trays causes steaming instead of browning.',
      'Make-ahead tip: assembled raw empanadas freeze beautifully. Freeze on a tray first, then bag. Bake straight from frozen at 400°F, adding about 5 extra minutes.',
    ],
    nutrition: {
      calories: '~200',
      protein: '~10g',
      carbs: '~18g',
      highlight: 'Per empanada · Baked, not fried',
    },
    equipment: 'Convection oven for even browning on every tray. Blackstone or wide cast iron ideal for the large-batch filling. Goya Tapas Discos (freezer/Hispanic foods section) — 5 packs for 48 empanadas.',
    garrettRating: 3,
    garrettTake: 'Good, worth experimenting with. The chimichurri carried it — don\'t skip that.',
  },
  {
    slug: 'chimichurri',
    title: 'Chimichurri',
    ethnicity: 'Argentine',
    category: 'Latin American',
    prepTime: '10 min (+ overnight rest)',
    cookTime: '0 min',
    servings: 8,
    description: 'Raw parsley, garlic, and oregano cut with red wine vinegar and good olive oil, finished with chili heat. Bright, punchy, and built for dunking empanadas — or anything off the Blackstone.',
    ingredients: [
      '2 cups packed flat-leaf parsley',
      '8 garlic cloves',
      '¼ cup fresh oregano (or 4 tsp dried)',
      '1 cup extra-virgin olive oil',
      '½ cup red wine vinegar',
      '2 tsp red pepper flakes',
      '1½ tsp salt',
    ],
    steps: [
      'Add parsley, garlic, oregano, chili flake, and salt to a blender or food processor.',
      'Pulse — don\'t run the blade continuously. You want a coarse, spoonable texture. Running it smooth bruises the parsley and turns it to baby food.',
      'Transfer to a jar and stir in the olive oil and vinegar by hand — keeps the sauce loose and rustic rather than a tight emulsion.',
      'Refrigerate overnight. The acid mellows the raw garlic and the flavors marry. Pull to room temperature before serving so the oil loosens back up.',
      'Serve as a dipping sauce alongside empanadas, or spoon over any grilled meat. Keeps refrigerated for one week.',
    ],
    nutrition: {
      calories: '~120',
      protein: '0g',
      carbs: '1g',
      highlight: 'Anti-Inflammatory Herbs & Olive Oil',
    },
    equipment: 'Ninja blender or food processor. A jar for storage — it only gets better as it sits.',
    garrettRating: 5,
    garrettTake: 'Perfect recipe. A must-make alongside the empanadas — it elevated the whole spread.',
  },
  {
    slug: 'smoked-pulled-chicken-thighs',
    title: 'Smoked pulled chicken thighs',
    ethnicity: 'American BBQ',
    category: 'BBQ',
    prepTime: '20 min (+ 1–2 hr dry rest)',
    cookTime: '3–4 hr at 225°F',
    servings: 6,
    description: 'Deeply smoky, pull-apart chicken thighs with a paprika-garlic bark. Set-and-forget on the pellet smoker, then pulled and finished with apple cider vinegar. Serve as sandwiches, over rice, or in tacos across the weekend.',
    ingredients: [
      '6–8 bone-in, skin-on chicken thighs',
      '2 tbsp smoked paprika',
      '1 tbsp garlic powder',
      '1 tbsp onion powder',
      '1 tsp cumin',
      '1 tsp black pepper',
      '1½ tsp kosher salt',
      '1 tbsp olive oil',
      'Hickory or apple wood pellets',
    ],
    steps: [
      'Mix all dry spices. Pat thighs completely dry — moisture is the enemy of bark. Coat lightly with olive oil, apply rub generously on all sides. Rest uncovered in the fridge 1–2 hours (or overnight) if time allows.',
      'Preheat smoker to 225°F with hickory or apple wood. Place thighs skin-side up directly on grates — no foil, you want full smoke exposure throughout.',
      'Smoke 3–4 hours until internal temp hits 165°F. Chicken thighs are forgiving — pulling at 175–180°F gives more pull-apart texture without drying out.',
      'Rest 15 minutes before pulling. Remove the skin (it softens during smoke), then pull with two forks. Toss with a splash of apple cider vinegar to brighten — optional but highly recommended.',
      'Serve as pulled chicken sandwiches on brioche, taco filling, over rice with pickled jalapeños, or chopped into a grain bowl.',
    ],
    nutrition: {
      calories: '~310',
      protein: '38g',
      carbs: '2g',
      highlight: 'High B Vitamins & Zinc',
    },
    equipment: 'Pellet smoker (hickory or apple wood). Meat thermometer. This is exactly the low-maintenance cook the smoker is built for — no babysitting once the temp stabilizes.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'turkey-burgers-blistered-jalapenos',
    title: 'Turkey burgers with blistered jalapeños',
    ethnicity: 'American',
    category: 'American',
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 4,
    description: 'Juicy turkey patties with pepper jack, smashed avocado, chipotle-yogurt spread, and jalapeños blistered hard on the Blackstone. Simple build, bold toppings.',
    ingredients: [
      '1½ lbs 93/7 ground turkey',
      '1 tsp garlic powder',
      '1 tsp Worcestershire sauce',
      '¾ tsp kosher salt',
      '½ tsp black pepper',
      'Neutral oil for the Blackstone',
      '4–5 jalapeños, halved lengthwise',
      'Pepper jack cheese, sliced',
      '2 ripe avocados',
      '4 brioche burger buns',
      '½ cup Greek yogurt',
      '1–2 tsp chipotle in adobo, minced',
      '½ tsp lime juice',
      'Pinch of garlic powder (for spread)',
    ],
    steps: [
      'Chipotle-yogurt spread: whisk Greek yogurt, minced chipotle, lime juice, and garlic powder. Season with salt. Refrigerate until service — it thickens slightly as it sits.',
      'Form patties: combine turkey with garlic powder, Worcestershire, salt, and pepper. Mix minimally — overworking makes turkey burgers dense. Form 4 patties slightly wider than your buns (they shrink). Press a shallow thumbprint in the center of each to prevent puffing.',
      'Blister jalapeños first: preheat Blackstone on high with a thin layer of oil. Place halved jalapeños cut-side down and leave alone 3–4 minutes until deeply charred. Flip, press briefly, 1 more minute. Pull and set aside — the char softens the heat and adds smokiness.',
      'Drop heat to medium-high. Oil the surface. Cook patties 5–6 minutes undisturbed — don\'t press them or you\'ll lose moisture. Flip once, add pepper jack immediately, dome to melt. Cook 4–5 more minutes to 165°F internal.',
      'Toast buns cut-side down on the Blackstone, 1–2 minutes.',
      'Build: chipotle-yogurt spread on both buns, patty with melted pepper jack, smashed avocado, blistered jalapeños. Serve immediately.',
    ],
    nutrition: {
      calories: '~490',
      protein: '42g',
      carbs: '~28g',
      highlight: 'Lean Turkey & Healthy Fats (avocado)',
    },
    equipment: 'Blackstone griddle. Two-zone approach — screaming hot for jalapeño blister, medium-high for patties. Dome lid for melting cheese.',
    garrettRating: 5,
    garrettTake: 'Best turkey burgers I\'ve ever made — guests agreed. The blistered jalapeños and chipotle-yogurt spread are the difference makers.',
  },
  {
    slug: 'shrimp-tacos-mango-jalapeno-salsa',
    title: 'Shrimp tacos with mango-jalapeño salsa & yogurt crema',
    ethnicity: 'Baja-Inspired',
    category: 'Latin American',
    prepTime: '15 min',
    cookTime: '10 min',
    servings: 4,
    description: 'Charred, spiced shrimp in warm corn tortillas with bright mango-jalapeño salsa and a cool lime-yogurt crema. Light, summery, and fast.',
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '1 tsp smoked paprika',
      '½ tsp cumin',
      '½ tsp garlic powder',
      '¼ tsp cayenne',
      '½ tsp kosher salt',
      '1 tbsp olive oil',
      '8 small corn tortillas',
      '1 ripe mango, small dice',
      '1–2 jalapeños, minced',
      '¼ red onion, fine dice',
      'Small handful cilantro, chopped',
      'Juice of 1½ limes',
      '½ cup Greek yogurt',
      '1 small garlic clove, grated',
      '1–2 tbsp water to thin',
      'Lime wedges for serving',
    ],
    steps: [
      'Mango salsa: combine mango, minced jalapeño, red onion, cilantro, juice of 1 lime, and a pinch of salt. Rest 10+ minutes — the lime juice softens the onion and melds the flavors.',
      'Yogurt crema: whisk Greek yogurt, remaining lime juice, grated garlic, and salt. Thin with water to a drizzleable consistency. Set aside.',
      'Season shrimp with smoked paprika, cumin, garlic powder, cayenne, salt, and olive oil. Don\'t marinate longer than 15 minutes — the acid will start cooking the proteins.',
      'Cook shrimp on a screaming hot Blackstone with oiled surface. Single layer — no crowding or they steam instead of sear. 90 seconds per side, pulling when they curl into a C and go opaque. A tight O means overcooked.',
      'Warm tortillas directly on the Blackstone, 30–45 seconds per side until lightly charred and pliable.',
      'Build: crema on tortilla, 3–4 shrimp, mango-jalapeño salsa, squeeze of lime. Serve immediately.',
    ],
    nutrition: {
      calories: '~380',
      protein: '34g',
      carbs: '~38g',
      highlight: 'Lean Protein & Vitamin C (mango)',
    },
    equipment: 'Blackstone griddle — high, dry heat for searing shrimp and charring tortillas simultaneously on different zones.',
    garrettRating: 5,
    garrettTake: 'Amazing on the tacos. The mango-jalapeño combo is a standout — bright, sweet, and spicy all at once.',
  },
  {
    slug: 'shrimp-tacos-charred-peach-salsa',
    title: 'Griddled shrimp tacos with charred peach salsa',
    ethnicity: 'Baja-Style',
    category: 'Latin American',
    prepTime: '25 min (+ 15 min brine)',
    cookTime: '15 min',
    servings: 4,
    description: 'Brined, spiced shrimp on a screaming-hot griddle with charred peach salsa, chimichurri crema, and a quick carrot-pepper slaw. Built from what\'s already in the kitchen.',
    ingredients: [
      '1.3 lb shrimp, peeled and deveined',
      '½ tsp baking soda (brine)',
      '1 tsp kosher salt, divided',
      '1½ tsp chili powder',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '½ tsp garlic powder',
      '2 tbsp avocado oil, divided',
      '3 firm-ripe peaches, halved and pitted',
      '½ onion, finely diced',
      '2 jalapeños, seeded and minced',
      '½ cup cilantro, chopped',
      'Juice of 3 limes',
      '1 tsp honey (optional, if peaches are underripe)',
      '2 carrots, julienned or grated',
      '1 bell pepper, thinly sliced',
      '½ cup Greek yogurt',
      '2 tbsp chimichurri',
      '12 corn or flour tortillas',
    ],
    steps: [
      'Brine the shrimp: toss with baking soda and half the salt. Rest 15 minutes, then rinse and pat completely dry. The alkaline brine prevents proteins from binding too tightly — that\'s what produces a snappy, plump texture. Drying is non-negotiable; wet shrimp steam instead of sear.',
      'Mix spice rub: combine chili powder, cumin, smoked paprika, and garlic powder. Toss dried shrimp with 1 tbsp avocado oil and the spice blend. Hold the remaining salt until after cooking.',
      'Char the peaches: griddle on high, lightly oiled. Lay halves cut-side down and leave alone 3–4 minutes until deeply marked — the sugars need to caramelize past golden to concentrate. Cool 5 minutes, then dice.',
      'Peach salsa: combine diced peaches, onion, jalapeño, cilantro, and juice of 2 limes. Add honey only if peaches taste flat. Salt just before serving — it draws water out of stone fruit fast and makes the salsa soupy.',
      'Quick slaw: toss carrots and bell pepper with remaining lime juice and a pinch of salt. Let sit while you cook — the acid softens the carrot slightly without cooking it.',
      'Chimichurri crema: whisk chimichurri into Greek yogurt with a squeeze of lime and a pinch of salt. Thin with a teaspoon of water if too thick to drizzle.',
      'Sear shrimp on a screaming hot griddle with remaining avocado oil. Single layer, no crowding. 90 seconds per side — pull when they form a loose C. Season with reserved salt off the heat.',
      'Char tortillas 20–30 seconds per side until blistered and pliable. Build: slaw first as a moisture barrier, then shrimp, peach salsa, crema drizzle, extra cilantro. Note: scrape the griddle between peaches and shrimp — residual sugar burns.',
    ],
    nutrition: {
      calories: '~410',
      protein: '28g',
      carbs: '~42g',
      highlight: 'Lean Shrimp & Charred Stone Fruit',
    },
    equipment: 'Blackstone griddle for staged high-heat cooking — chars the peaches, sears the shrimp, and toasts the tortillas in sequence on one hot surface.',
    garrettRating: 4,
    garrettTake: 'A good salsa — a great example of using in-season fruit to build something zesty and fresh for tacos.',
  },
  {
    slug: 'chicken-sausage-meat-sauce',
    title: 'Deconstructed chicken sausage meat sauce',
    ethnicity: 'Italian-American',
    category: 'European',
    prepTime: '10 min',
    cookTime: '30 min',
    servings: 4,
    description: 'Italian-style chicken sausage browned hard in cast iron, deglazed, and simmered into a real meat sauce. Jarred marinara becomes legitimately good once you build fond under it and give it time to reduce.',
    ingredients: [
      '1 lb Italian-style chicken sausage links, casings removed',
      '1 tbsp avocado oil',
      '½ onion, diced',
      '3–4 garlic cloves, minced',
      'Pinch of red pepper flakes',
      '¼ cup red wine, chicken stock, or water (for deglazing)',
      '1 jar (24 oz) marinara sauce',
      '½ tsp salt + black pepper to taste',
      'Pinch of sugar, or 1 carrot grated (to round out acidity)',
      '1 lb spaghetti',
      'Reserved pasta water',
      'Fresh basil, torn',
      'Grated Parmesan and olive oil to finish',
    ],
    steps: [
      'Slit the casings and squeeze the sausage out. Loose sausage gives far more surface area for browning than sliced coins, and the fat renders into the sauce instead of staying trapped inside.',
      'Brown hard in cast iron over medium-high heat with a thin film of avocado oil. Break into rough chunks and leave alone 3–4 minutes — you want deep brown crust, not gray crumble. Break down further only after the first side has color. Total 6–8 minutes.',
      'Add onion, garlic, and red pepper flakes to the rendered fat. Cook 3 minutes until the onion turns translucent and picks up the browned bits.',
      'Deglaze with a splash of red wine, stock, or water — about ¼ cup. Scrape the fond off the bottom. This is the single step that separates "jarred sauce with meat in it" from an actual meat sauce.',
      'Add the marinara and rinse the jar with a few tablespoons of water into the pan. Season with salt, pepper, and a pinch of sugar or grated carrot to balance the acidity. Taste before adding more salt — the sausage is already salty.',
      'Simmer uncovered 20–25 minutes on the lowest heat that still bubbles. It will darken and tighten. If it looks thin at 20 minutes, keep going.',
      'Reserve a cup of pasta water before draining the spaghetti. Toss drained pasta in the pan with the sauce and a few splashes of starchy water over medium heat for 60 seconds — the starch emulsifies the rendered fat so the sauce clings to the noodles instead of pooling.',
      'Fold in half the basil off the heat — tear, don\'t chop; a knife bruises basil and blackens the edges. Serve topped with remaining basil, grated Parmesan, and a drizzle of olive oil.',
    ],
    nutrition: {
      calories: '~560',
      protein: '32g',
      carbs: '~68g',
      highlight: 'Lean Sausage & Slow-Built Fond',
    },
    equipment: 'Cast iron skillet for the sear — holds heat well enough to build real fond rather than steaming the meat.',
    garrettRating: 5,
    garrettTake: 'Amazing. Deglazing the pan and building the fond is what makes this special — jarred sauce becomes genuinely great.',
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}