export type Recipe = {
  slug: string;
  title: string;
  ethnicity: string;
  category: 'Asian' | 'Middle Eastern' | 'Latin American' | 'European' | 'BBQ' | 'American';
  prepTime: string;
  cookTime: string;
  servings: number;
  description: string;
  ingredients: string[];
  steps: string[];
  nutrition: {
    calories: string;
    protein: string;
    carbs: string;
    highlight: string;
  };
  equipment?: string;
  garrettRating: number;
  garrettTake: string;
};

export const recipes: Recipe[] = [
  {
    slug: 'thai-style-pineapple-fried-rice',
    title: 'Thai-style pineapple fried rice',
    ethnicity: 'Southeast Asian — Thai',
    category: 'Asian',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 6,
    description: 'Savory-sweet jasmine rice wok-tossed with fresh pineapple, shrimp, and toasted cashews — finished with fish sauce and a hit of lime. Leftovers hold beautifully.',
    ingredients: [
      '3 cups jasmine rice (cooked day-ahead, chilled)',
      '1 lb large shrimp, peeled and deveined',
      '2 cups fresh pineapple, diced (use your pineapple)',
      '3 eggs',
      '1 cup frozen peas',
      '4 scallions, sliced',
      '4 garlic cloves, minced',
      '1 tbsp fresh ginger, grated',
      '3 tbsp soy sauce',
      '1 tbsp fish sauce',
      '1 tbsp sesame oil',
      '2 tbsp neutral oil (avocado or canola)',
      '½ cup roasted cashews',
      '1 lime, juiced (use your lemons if preferred)',
      'Fresh cilantro to finish',
    ],
    steps: [
      'Cook jasmine rice a day ahead and refrigerate uncovered. Cold, dry rice is essential — fresh rice holds too much moisture and steams instead of frying, producing clumped, mushy results.',
      'Heat a large pan or wok over high heat until smoking. Add 1 tbsp neutral oil. Sear shrimp 90 seconds per side — don\'t crowd. Remove and set aside.',
      'Add remaining oil. Sauté garlic and ginger 30 seconds until fragrant, then add pineapple and cook 2 minutes to caramelize the edges slightly.',
      'Push everything to the sides. Crack eggs into the center and scramble until just set, then fold into the pineapple mixture.',
      'Add cold rice. Press it flat against the pan and let it sit 60–90 seconds untouched — this creates the lightly crisped crust that distinguishes good fried rice. Toss and repeat once.',
      'Add soy sauce, fish sauce, and sesame oil. Toss to coat evenly. Fold in peas, scallions, and shrimp.',
      'Finish with lime juice and cashews. Top with cilantro. Serve immediately, or refrigerate — reheats well in a hot pan.',
    ],
    nutrition: {
      calories: '~420',
      protein: '28g',
      carbs: '~52g',
      highlight: 'High Vitamin C (pineapple)',
    },
    equipment: 'The Blackstone griddle is ideal here — its large surface area lets you spread all the rice flat for simultaneous crust formation. A standard wok or large skillet works, but you\'ll need to work in batches to avoid steaming.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'smoker-pizza-on-homemade-naan-white-garlic-chicken',
    title: 'Smoker pizza on homemade naan — white garlic + chicken',
    ethnicity: 'South Asian base · American BBQ technique',
    category: 'BBQ',
    prepTime: '25 min active prep + 1 hr dough rest',
    cookTime: '60 min',
    servings: 4,
    description: 'Pillowy hand-stretched naan acts as the crust — topped with roasted garlic cream, smoked chicken thighs, fresh mozzarella, and a lemon-herb finish. The pellet smoker adds a subtle wood note that a conventional oven never touches.',
    ingredients: [
      // Naan dough
      '2¼ tsp instant yeast',
      '1 cup warm water',
      '3 cups all-purpose flour',
      '½ cup plain Greek yogurt',
      '2 tbsp olive oil',
      '1 tsp salt',
      '1 tsp sugar',
      // Toppings
      '3 boneless skinless chicken thighs',
      '6 garlic cloves',
      '4 oz cream cheese, softened',
      '¼ cup heavy cream',
      '8 oz fresh mozzarella, torn',
      '1 lemon, zested and juiced (use your lemons)',
      'Fresh thyme or rosemary',
      'Olive oil, salt, pepper, red pepper flakes',
      'Fresh arugula (optional finish)',
    ],
    steps: [
      'Make naan dough: combine yeast, sugar, and warm water — rest 5 minutes until foamy. Mix in flour, yogurt, olive oil, and salt until a shaggy dough forms. Knead 5–6 minutes until smooth and slightly tacky. Cover and rest 1 hour until doubled.',
      'While dough rests, preheat pellet smoker to 275°F with a mild wood like apple or cherry. Season chicken thighs with salt, pepper, and olive oil. Smoke 45–55 minutes until internal temp hits 165°F. Rest 10 minutes, then slice thin.',
      'Roasted garlic sauce: wrap garlic cloves in foil with a drizzle of olive oil — place directly on the smoker grate the last 30 minutes. When soft, squeeze cloves out and blend with cream cheese and heavy cream until smooth. Season with salt and lemon zest.',
      'Divide dough into 4 equal portions. On a lightly floured surface, stretch or roll each into a roughly oval shape, about ¼ inch thick. Don\'t aim for perfect circles — rustic edges cook better.',
      'Crank smoker to 450°F (or as high as it goes). Place naan directly on the grates. Cook 3–4 minutes until the bottom has grill marks and is set but not fully cooked through.',
      'Flip naan. Working quickly, spread garlic cream, top with torn mozzarella and sliced chicken. Close the lid and cook 4–5 more minutes until cheese is melted and edges are golden.',
      'Remove from smoker. Finish with lemon juice, red pepper flakes, and fresh herbs. Top with arugula if using — it wilts perfectly on the residual heat.',
    ],
    nutrition: {
      calories: '~560',
      protein: '38g',
      carbs: '~48g',
      highlight: 'High Selenium (chicken)',
    },
    equipment: 'The pellet smoker does real work here — both the chicken and garlic absorb smoke during the low-temp phase, then the high-heat finish blisters the naan directly on the grates. A pizza stone placed inside the smoker during preheat is optional but adds bottom crunch.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'moroccan-spiced-turkey-skillet-with-lemon-couscous',
    title: 'Moroccan-spiced turkey skillet with lemon couscous',
    ethnicity: 'North African — Moroccan',
    category: 'Middle Eastern',
    prepTime: '10 min',
    cookTime: '30 min',
    servings: 4,
    description: 'Ground turkey simmered with warm spices — cumin, coriander, cinnamon — in a tomato-chickpea sauce. Finished with preserved-style lemon brightness and served over fluffy couscous. Bold, warming, and weeknight-fast.',
    ingredients: [
      '1.25 lbs lean ground turkey',
      '1 can (15 oz) chickpeas, drained',
      '1 can (14 oz) crushed tomatoes',
      '1 medium yellow onion, diced',
      '4 garlic cloves, minced',
      '1 tsp each: cumin, coriander, smoked paprika',
      '½ tsp cinnamon',
      '¼ tsp cayenne (adjust to taste)',
      '1 cup chicken broth',
      '2 lemons — zest both, juice one (use your lemons)',
      '1½ cups couscous',
      '1¾ cups boiling water or broth (for couscous)',
      'Fresh parsley or mint to finish',
      '2 tbsp olive oil, salt, pepper',
    ],
    steps: [
      'Bloom the spices: heat olive oil in a large skillet over medium-high. Add onion and cook 4–5 minutes until softened and lightly golden. Add garlic and all dry spices — cook 60 seconds, stirring constantly. Blooming spices in fat unlocks fat-soluble compounds and deepens flavor significantly.',
      'Add ground turkey. Break into small pieces and cook until no pink remains, about 5–6 minutes. Don\'t rush this — full browning develops the Maillard crust that adds depth to the sauce.',
      'Pour in crushed tomatoes, chickpeas, and chicken broth. Stir to combine, scraping any fond from the pan bottom. Reduce heat to medium-low and simmer uncovered 15 minutes until sauce thickens.',
      'While sauce simmers, make couscous: place in a heatproof bowl, pour boiling water or broth over, cover tightly with plastic wrap or a plate. Rest exactly 5 minutes. Fluff with a fork, add lemon zest and a drizzle of olive oil.',
      'Finish the skillet with lemon juice. Taste and adjust salt. The lemon does the work preserved lemon would — bright acidity cuts the warm spices cleanly.',
      'Serve turkey mixture over couscous. Top with fresh parsley or mint. Optionally add a spoonful of Greek yogurt — it cools the heat and adds creaminess without extra cooking.',
    ],
    nutrition: {
      calories: '~470',
      protein: '42g',
      carbs: '~50g',
      highlight: 'High Fiber (chickpeas)',
    },
    equipment: 'No specialty equipment needed here — this is a pure skillet meal. The convection oven setting (if finishing in a covered baking dish) can deepen the sauce further, but stovetop alone is excellent and faster.',
    garrettRating: 5,
    garrettTake: 'This was amazing. Make sure to char the turkey and don\'t be afraid of the cinnamon. Use a timer to make sure you let the spices & garlic cook the desired amount before adding the ground turkey. A standout recipe.',
  },
  {
    slug: 'grilled-chicken-caesar-wraps',
    title: 'Grilled chicken caesar wraps',
    ethnicity: 'Italian-American — homemade dressing',
    category: 'European',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 6,
    description: 'Smoky grilled chicken over crisp romaine, tossed in a punchy homemade caesar — anchovy, garlic, lemon, and parmesan blended into a silky emulsion. Wrapped tight in a toasted flour tortilla with shaved parm and cracked black pepper.',
    ingredients: [
      '3 large chicken breasts',
      '1 tsp garlic powder',
      '1 tsp smoked paprika',
      'Salt & black pepper',
      'Olive oil',
      '4 anchovy fillets',
      '2 garlic cloves',
      '2 egg yolks',
      '2 tbsp fresh lemon juice',
      '1 tsp Dijon mustard',
      '1 tsp Worcestershire sauce',
      '½ cup olive oil (for dressing)',
      '¼ cup grated parmesan',
      '6 large flour tortillas',
      '3 cups romaine, chopped',
      '½ cup parmesan, shaved',
      'Cracked black pepper',
    ],
    steps: [
      'Pound chicken breasts to even ¾" thickness. Season with garlic powder, smoked paprika, salt, and pepper. Let sit while you make the dressing.',
      'Make the dressing: add anchovies, garlic, egg yolks, lemon juice, Dijon, and Worcestershire to a blender. Blend until smooth — about 20 seconds. With the blender running, stream olive oil in slowly. This gradual addition is what creates the emulsion; dump it all at once and it\'ll break. Finish with parmesan, pulse twice, taste for salt.',
      'Grill chicken on the Blackstone or cast iron over medium-high heat, 5–6 min per side. Pull at 160°F internal, rest 5 min, slice thin against the grain.',
      'Toss romaine with just enough dressing to coat — overdressing makes the wrap soggy. Hold extra dressing on the side.',
      'Toast tortillas on the Blackstone 30 sec per side.',
      'Build: dressed romaine, sliced chicken, shaved parmesan, cracked pepper. Wrap tight and slice on the diagonal.',
    ],
    nutrition: {
      calories: '~490',
      protein: '40g',
      carbs: '~30g',
      highlight: 'High Protein & Omega-3s (anchovies)',
    },
    equipment: 'Blender (Ninja preferred) for emulsifying the dressing. Blackstone griddle for simultaneous tortilla toasting and chicken searing.',
    garrettRating: 4,
    garrettTake: 'Solid option, easily scaleable, and the DIY dressing is worth it.',
  },
  {
    slug: 'korean-chicken-broccoli-plate',
    title: 'Korean chicken & broccoli plate',
    ethnicity: 'East Asian — Korean',
    category: 'Asian',
    prepTime: '20 min',
    cookTime: '20 min',
    servings: 4,
    description: 'A dynamic three-component plate: cool marinated cucumber salad, crispy chow mein noodles, and glossy gochujang-glazed chicken over broccoli. Bold, textured, and deeply satisfying.',
    ingredients: [
      '1 large cucumber, sliced thin',
      '1 tbsp rice vinegar',
      '1 tsp sesame oil',
      '½ tsp chili flake (gochugaru or red pepper flake)',
      '1 tsp soy sauce',
      '1 tsp honey',
      '1 tsp sesame seeds',
      '1 green onion, sliced',
      '8 oz lo mein noodles (or spaghetti)',
      '2 tbsp soy sauce (for noodles)',
      '1 tbsp oyster sauce',
      '1 tsp sesame oil (for sauce)',
      '1 tsp gochujang',
      '3 garlic cloves, minced',
      '2 stalks celery, sliced thin on a bias',
      '½ yellow onion, sliced thin',
      '1 tbsp neutral oil (for noodles)',
      '1 green onion, sliced (garnish)',
      '1.5 lbs chicken breast',
      '2 cups broccoli florets',
      '1 bell pepper, sliced',
      '2 tbsp gochujang (for chicken)',
      '2 tbsp soy sauce (for chicken)',
      '1 tbsp honey (for chicken)',
      '1 tbsp rice vinegar (for chicken)',
      '1 tsp sesame oil (for chicken)',
      '3 garlic cloves, minced (for chicken)',
      '1 tsp fresh ginger, grated',
      '1 tbsp neutral oil (for chicken)',
      'Salt & pepper',
      'Sesame seeds & sliced green onion to finish',
    ],
    steps: [
      'Prepare cucumber salad first: slice cucumber thin. Toss with a pinch of salt and let sit 10 min — this draws out water so the dressing doesn\'t dilute. Pat dry.',
      'Whisk rice vinegar, sesame oil, soy sauce, honey, and chili flake. Toss with cucumber. Top with sesame seeds and green onion. Refrigerate until serving.',
      'Make noodle sauce: mix soy sauce, oyster sauce, sesame oil, and gochujang in a small bowl. Set aside.',
      'Cook noodles until just al dente — 1 minute less than the package says. They\'ll finish cooking in the pan. Drain and toss with a drop of oil to prevent sticking.',
      'Heat wok or large skillet over high heat until smoking. Add neutral oil for noodles, then celery and onion. Stir-fry 2–3 min — you want some color on the onion but celery should stay crisp. Add garlic, stir 30 seconds.',
      'Add noodles and sauce. Toss constantly for 1–2 min until everything is coated and noodles have a little char. Finish with green onion.',
      'While noodles cook, boil broccoli 90 seconds, then transfer to ice water. This sets the bright green color and par-cooks it.',
      'Make chicken glaze: whisk gochujang, soy sauce, honey, rice vinegar, sesame oil, garlic, and ginger. Set aside.',
      'Slice chicken breast against the grain into ½-inch thick planks. Pat completely dry. Season with salt and pepper.',
      'Heat skillet or Blackstone over high heat with neutral oil. Sear chicken planks 3 min per side undisturbed. Work in batches if needed; crowding drops pan temp.',
      'Remove chicken to a plate. In the same pan, add bell pepper and blanched broccoli. Toss 1–2 min. Return chicken, pour glaze over everything, and toss for 30–45 seconds until everything is coated and glossy.',
      'Plate: arrange vegetables first. Lay sliced chicken over the top. Spoon remaining glaze over the chicken. Finish with sesame seeds and green onion.',
    ],
    nutrition: {
      calories: '~490',
      protein: '38g',
      carbs: '~52g',
      highlight: 'High Protein & Vitamin C',
    },
    equipment: 'Wok or large skillet for high-heat stir-frying. Blackstone optional but ideal for simultaneous noodle and chicken cooking.',
    garrettRating: 2.5,
    garrettTake: 'Solid middle-of-the-road dish that\'s very healthy and carried by the sauce addition at the end. The chow mein was also good. A promising recipe we\'ll be revisiting and finding ways to enhance.',
  },
  {
    slug: 'turkish-chicken-shawarma-bowls',
    title: 'Turkish chicken shawarma bowls',
    ethnicity: 'Turkish — Middle Eastern',
    category: 'Middle Eastern',
    prepTime: '20 min (+ 20 min marinade)',
    cookTime: '15 min',
    servings: 6,
    description: 'Warm spiced chicken over herbed rice with a tangy yogurt-garlic sauce. Bold, aromatic, and satisfying without being heavy.',
    ingredients: [
      '2 lbs chicken breast, sliced thin',
      '1 cup 5% Greek yogurt (divided — ½ for marinade, ½ for sauce)',
      '2 tbsp olive oil',
      '1 tbsp cumin',
      '1 tbsp smoked paprika',
      '1 tsp turmeric',
      '1 tsp coriander',
      '1 tsp garlic powder',
      'Salt & pepper',
      '2 cups long-grain white rice',
      '1 can (15 oz) chickpeas, drained',
      '1 cucumber, diced',
      '2 roma tomatoes, diced',
      'Fresh parsley',
      '4 garlic cloves',
      '1 lemon',
    ],
    steps: [
      'Combine ½ cup yogurt, olive oil, cumin, paprika, turmeric, coriander, garlic powder, salt, pepper, and juice of ½ lemon. Coat sliced chicken and marinate 20 min minimum (up to overnight). The yogurt\'s lactic acid tenderizes without making the meat mushy.',
      'Cook rice per package instructions. Fluff and fold in a handful of chopped parsley and a squeeze of lemon.',
      'Get your Blackstone or cast iron ripping hot. Cook chicken in a single layer 3–4 min per side. Don\'t crowd — you want Maillard char on the edges, not steaming. Work in batches if needed.',
      'Make yogurt sauce: mix remaining ½ cup yogurt with 2 minced garlic cloves, juice of ½ lemon, pinch of salt. Thin with 1–2 tbsp water to drizzle consistency.',
      'Build bowls: rice base → chickpeas → sliced chicken → cucumber & tomato → yogurt sauce → fresh parsley. Store components separately for best leftover quality.',
    ],
    nutrition: {
      calories: '~520',
      protein: '42g',
      carbs: '~52g',
      highlight: 'High Protein & Probiotics (yogurt)',
    },
    equipment: 'Cast iron skillet or Blackstone griddle for excellent char on the chicken.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'korean-gochujang-pork-tenderloin',
    title: 'Korean gochujang pork tenderloin',
    ethnicity: 'Korean',
    category: 'Asian',
    prepTime: '10 min',
    cookTime: '35 min',
    servings: 4,
    description: 'Tender, juicy pork glazed in a savory-sweet gochujang sauce with sesame and ginger. A little heat, a lot of depth.',
    ingredients: [
      '1.5 lbs pork tenderloin',
      '3 tbsp gochujang',
      '2 tbsp low-sodium soy sauce',
      '1 tbsp sesame oil',
      '1 tbsp honey',
      '1 tbsp rice vinegar',
      '1 tbsp fresh ginger, grated',
      '3 garlic cloves, minced',
      '2 tsp sesame seeds',
      '3 green onions, sliced',
      '1 lb broccolini or broccoli',
      '1 tbsp neutral oil (avocado or grapeseed)',
      'Salt & pepper',
    ],
    steps: [
      'Whisk gochujang, soy sauce, sesame oil, honey, rice vinegar, ginger, and garlic together. Reserve 2 tbsp separately for finishing.',
      'Pat pork dry — moisture is the enemy of a good sear. Season with salt. Coat with half the glaze.',
      'Heat cast iron over high heat with neutral oil. Sear tenderloin 2 min per side (4 sides) until a dark crust forms. This step builds flavor that roasting alone can\'t.',
      'Transfer to convection oven at 400°F. Roast 12–15 min until internal temp hits 145°F. Convection circulates hot air for even cooking without drying the center. Rest 5 min before slicing.',
      'Toss broccolini in oil, salt, pepper. Roast alongside pork last 10 min until edges are charred.',
      'Slice tenderloin against the grain. Drizzle with reserved glaze. Top with sesame seeds and green onions.',
    ],
    nutrition: {
      calories: '~440',
      protein: '38g',
      carbs: '~20g',
      highlight: 'Lean Cut & Gut-Friendly Gochujang',
    },
    equipment: 'Convection oven for even roasting. Cast iron for initial sear.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'greek-turkey-meatballs-lemon-yogurt-sauce',
    title: 'Greek turkey meatballs with lemon-yogurt sauce',
    ethnicity: 'Greek',
    category: 'European',
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 4,
    description: 'Herb-packed turkey meatballs over orzo with a bright, creamy yogurt sauce spiked with lemon and dill. Fresh, clean, satisfying.',
    ingredients: [
      '1.25 lbs ground turkey',
      '½ cup 5% Greek yogurt (for sauce)',
      '¼ cup breadcrumbs (panko preferred)',
      '1 egg',
      '3 garlic cloves, minced (divided)',
      '1 tsp dried oregano',
      '1 tsp cumin',
      '½ tsp cinnamon',
      'Salt & pepper',
      'Fresh dill (6 tbsp chopped, divided)',
      'Fresh mint',
      '1 lemon',
      '1 lb orzo',
      '2 cups baby spinach',
      '½ red onion, sliced thin',
      '½ cup kalamata olives, halved',
      '2 tbsp olive oil',
    ],
    steps: [
      'Combine turkey, breadcrumbs, egg, 2 minced garlic cloves, oregano, cumin, cinnamon, 2 tbsp chopped dill, salt, and pepper. Mix until just combined — overworking develops protein strands that make meatballs tough. Roll into 1.5-inch balls.',
      'Heat olive oil in an oven-safe skillet over medium-high. Sear meatballs 2 min per side for color, then transfer skillet to 400°F convection oven for 10–12 min. Or bake on a sheet pan at 425°F for 18–20 min.',
      'Cook orzo per package instructions (usually 8–9 min). Drain, toss with a drizzle of olive oil, lemon zest, and baby spinach — residual heat wilts the spinach.',
      'Whisk ½ cup yogurt with 1 minced garlic clove, juice of 1 lemon, remaining fresh dill, salt, and pepper. Thin with 1–2 tbsp water if needed.',
      'Plate: orzo base → meatballs → yogurt sauce → red onion, olives, fresh mint. Finish with lemon zest and a drizzle of good olive oil.',
    ],
    nutrition: {
      calories: '~460',
      protein: '36g',
      carbs: '~48g',
      highlight: 'Lean Protein & Anti-Inflammatory Herbs',
    },
    equipment: 'Oven-safe skillet or sheet pan for finishing meatballs.',
    garrettRating: 3.7,
    garrettTake: 'Solid take on a Shannon classic. Very healthy meal. The herbs are well-balanced and the yogurt sauce is bright. We added a side of sautéed kale.',
  },
  {
    slug: 'chicken-avocado-bacon-wraps',
    title: 'Chicken avocado bacon wraps',
    ethnicity: 'American — Tex-Mex inspired',
    category: 'American',
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 6,
    description: 'Smoky bacon, creamy avocado, and seasoned grilled chicken in a toasted flour tortilla. Bright lime crema keeps it fresh — satisfying without feeling heavy.',
    ingredients: [
      '3 large chicken breasts',
      '6 strips thick-cut bacon',
      '3 ripe avocados',
      '6 large flour tortillas',
      '2 cups romaine, shredded',
      '1 cup cherry tomatoes, halved',
      '½ red onion, thin sliced',
      '½ cup sour cream',
      '1 lime',
      '1 tsp cumin',
      '1 tsp smoked paprika',
      'Salt & pepper',
      'Olive oil',
    ],
    steps: [
      'Season chicken breasts with cumin, smoked paprika, salt, and pepper. Let sit 10 min — even a short rest lets the seasoning penetrate past the surface.',
      'Pound chicken to even thickness (about ¾") with a meat mallet or heavy pan. Uniform thickness = even cook, no dry edges.',
      'Sear chicken in a hot cast iron or on the Blackstone over medium-high heat, 5–6 min per side. Pull at 160°F internal — carryover brings it to 165°F. Rest 5 min, then slice against the grain.',
      'Render bacon in a skillet over medium heat until crisp. Drain on paper towels. Reserve 1 tsp fat if desired for toasting tortillas.',
      'Whisk sour cream with lime juice, a pinch of salt, and a pinch of cumin. This lime crema is your sauce.',
      'Mash avocado with salt and a squeeze of lime. Rough mash — not guacamole smooth.',
      'Toast tortillas directly on the Blackstone or dry skillet 30 sec per side. Adds texture and prevents sogginess.',
      'Build: spread avocado, layer chicken, bacon, romaine, tomatoes, onion, drizzle crema. Wrap tight and slice on the diagonal.',
    ],
    nutrition: {
      calories: '~520',
      protein: '38g',
      carbs: '~35g',
      highlight: 'Healthy Fats (avocado) & Potassium',
    },
    equipment: 'Blackstone griddle ideal for simultaneous tortilla toasting and chicken searing.',
    garrettRating: 0,
    garrettTake: '',
  },
  {
    slug: 'shredded-chicken-tacos',
    title: 'Shredded chicken tacos',
    ethnicity: 'Mexican — braised & pulled',
    category: 'Latin American',
    prepTime: '15 min',
    cookTime: '40 min',
    servings: 4,
    description: 'Chile-braised chicken thighs pulled into tender, saucy strands. Loaded into warm corn tortillas with pickled red onion, cotija, and avocado crema — bold and deeply savory.',
    ingredients: [
      '2 lbs boneless chicken thighs',
      '1 can (14 oz) fire-roasted tomatoes',
      '3 chipotle peppers in adobo',
      '4 garlic cloves',
      '1 white onion',
      '1 tsp cumin',
      '1 tsp oregano (Mexican preferred)',
      '1 tsp smoked paprika',
      '½ cup chicken stock',
      '12 small corn tortillas',
      '1 avocado',
      '½ cup sour cream',
      '1 lime',
      '½ cup cotija cheese, crumbled',
      'Fresh cilantro',
      '1 red onion (for pickling)',
      'White vinegar',
      'Salt & olive oil',
    ],
    steps: [
      'Quick-pickle the red onion first: thin-slice, cover with white vinegar, juice of ½ lime, and a pinch of salt. 20 min minimum — they\'ll stay crisp and lose the raw bite.',
      'Blend fire-roasted tomatoes, chipotles, garlic, and ½ the white onion until smooth. This is your braising liquid.',
      'Season chicken thighs generously with salt, cumin, oregano, and smoked paprika.',
      'Sear thighs in a hot Dutch oven or heavy skillet with oil — 3 min per side. You\'re building fond, not cooking through. Don\'t skip this step; it adds depth the braise alone won\'t.',
      'Add blended sauce and chicken stock. Bring to a simmer, cover, and cook 25–30 min over medium-low until chicken shreds easily. The collagen in thighs keeps the meat moist through the braise.',
      'Remove chicken, shred with two forks, then return to the sauce. Simmer uncovered 5 min to let everything reduce and coat.',
      'Blend avocado, sour cream, lime juice, and a pinch of salt into a smooth crema.',
      'Char corn tortillas directly over a gas burner or on the Blackstone — 30 sec per side. Charring adds a slight bitterness that balances the rich braised chicken.',
      'Build tacos: chicken, avocado crema, pickled onion, cotija, cilantro.',
    ],
    nutrition: {
      calories: '~580',
      protein: '42g',
      carbs: '~38g',
      highlight: 'High Protein & Capsaicin (Chipotle)',
    },
    equipment: 'Dutch oven or heavy braising pot. Blender for avocado crema.',
    garrettRating: 3.5,
    garrettTake: 'Solid take on a Reilly family classic. The simmering of the chicken pre-shredding is an amazing addition. Adobo peppers make it spicy and smoky.',
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}